#!/bin/bash
# Part of the 'yocto_tools' GitHub repo
# 'A small, simple and useful tool collection for Yocto'
#  https://github.com/kaiwan/yocto_tools
# (c) Kaiwan NB, kaiwanTECH
# License: MIT
export name=$(basename "$0")
PFX=$(dirname "$(which "$0")")    # dir in which the common code and tools reside
source "${PFX}"/common || {
  echo "${name}: could not source 'common' script, aborting..." ; exit 1
}
setup_env #-q

#echo "OLDER_VER = ${OLDER_VER}"
SPEC=../meta*/recipes*/images/*.bb
[[ ${OLDER_VER} -eq 0 ]] && SPEC=${UPSTREAM_LAYERS}/openembedded-core/meta*/recipes*/images/*.bb

echo
printf "%81s\n" "IMAGE RECIPE Directory"
PREV=""
for IMG in $(ls ${SPEC})
do
	IMGDIR=$(dirname ${IMG})
	printf "%-40s " $(basename ${IMG}) 
	[[ "${IMGDIR}" = "${PREV}" ]] && printf " \n" || printf ": %s\n" ${IMGDIR}
	PREV=${IMGDIR}
done

exit 0
