#!/bin/bash
# Part of the 'yocto_tools' GitHub repo
# 'A small, simple and useful tool collection for Yocto'
#  https://github.com/kaiwan/yocto_tools
# (c) Kaiwan NB, kaiwanTECH
# License: MIT
export name=$(basename "$0")
PFX=$(dirname "$(which "$0")")    # dir in which the common code and tools reside
source "${PFX}"/common || {
  echo "${name}: could not source 'common' script, aborting..." ; exit 1
}
setup_env #-q

for IMG in $(ls ../meta*/recipes*/images/*.bb)
do
	printf "%-36s: %s\n" $(basename ${IMG}) $(dirname ${IMG})
	#echo "$(basename ${IMG})"
done

exit 0
