#!/bin/bash
# Part of the 'yocto_tools' GitHub repo
# 'A small, simple and useful tool collection for Yocto'
#  https://github.com/kaiwan/yocto_tools
# (c) Kaiwan NB, kaiwanTECH
# License: MIT
export name=$(basename "$0")
MNT=/mnt/yocto_rootfs
if mount|grep ${MNT} ; then
	echo "${name}: already mounted?"
	exit 1
fi

PFX=$(dirname "$(which "$0")")    # dir in which the common code and tools reside
source "${PFX}"/common || {
  echo "${name}: could not source 'common' script, aborting..." ; exit 1
}
setup_env #-q

EXT4_IMG=$(ls -1t tmp/deploy/images/${MACHINE}/${IMAGE_BASENAME}-${MACHINE}.ext[34] |head -n1)
[[ ! -f ${EXT4_IMG} ]] && die "couldn't fetch ext[34] image file path"
#echo "EXT4_IMG = $EXT4_IMG"
EXT4_IMG=$(realpath ${EXT4_IMG})
echo "Loop mounting this file
${EXT4_IMG}
as the rootfs, on mount point ${MNT} ...
"

sudo mkdir -p ${MNT} 2>/dev/null
sudo umount ${MNT}/ 2>/dev/null || true
sudo mount -o loop ${EXT4_IMG} ${MNT}/ || die "loop mount failed" && true
df -h |grep "${MNT}"
echo "Mounted; *** DON'T forget to umount it when done !!! ***"
exit 0
