#!/bin/bash
# Part of the 'yocto_tools' GitHub repo
# 'A small, simple and useful tool collection for Yocto'
#  https://github.com/kaiwan/yocto_tools
# (c) Kaiwan NB, kaiwanTECH
# License: MIT
export name=$(basename "$0")
MOUNT_POINT=/mnt/yocto_rootfs
if mount|grep ${MOUNT_POINT} ; then
	echo "${name}: already mounted?"
	exit 1
fi

PFX=$(dirname "$(which "$0")")    # dir in which the common code and tools reside
source "${PFX}"/common || {
  echo "${name}: could not source 'common' script, aborting..." ; exit 1
}
setup_env #-q

# FIXME: select a given rootfs based on a image basename (as there can be several)
EXT_IMG=$(ls -1t ${TMPD}/deploy/images/${MACHINE}/${IB}-${MACHINE}.*ext[34] |head -n1 || die "couldn't fetch any ext[34] format image file")
#echo "EXT_IMG = $EXT_IMG"
EXT_IMG=$(realpath ${EXT_IMG})
echo "Loop mounting this file
${EXT_IMG}
as the rootfs, on mount point ${MOUNT_POINT} ...
"

sudo mkdir -p ${MOUNT_POINT} 2>/dev/null
sudo umount ${MOUNT_POINT}/ 2>/dev/null || true
sudo mount -o loop ${EXT_IMG} ${MOUNT_POINT}/ || die "loop mount failed" && true
df -h |grep "${MOUNT_POINT}"
echo "Mounted; *** DON'T forget to umount it when done !!! ***"
exit 0
